### ISSUE TITLE
Should we allow the addition of custom classes? Discuss.

### ISSUE THREAD

**Issue by jpstevens** [uswitch/ustyle-react#16]
**Option 1:** Custom class passed to component:

```
<USP color='blue' text='Hello' className='my-custom-class'/>
```

**Option 2:** Wrapping component to add custom classes:

```
<CustomUSP className='my-custom-class'>
  <USP color='blue' text='Hello' />
</CustomUSP>
```

**Comment by annez** [comment]
It needs to be option 1. This is a larger discussion that should involve the questions: 

* Do we really need prop types 
* Can we whitelist prop types that are required but let everything else through?

This is becoming quite a problem especially when you want to just add arbitrary data-elements for GTM even capture. I don't think we should ever be constraining the attributes that are passed down the components, especially as we are then by definition having to copy paste HTML standards spec.

**Comment by jpstevens** [comment]
The HOF has spoken.

Closing this in favour of https://github.com/uswitch/ustyle-react/issues/36
